=== Ancro/massive-nemesis/CRNH0203-2013-CO_Dinosaur_2_E.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT wbanno (#PCDATA)>
<!ELEMENT utc_t (#PCDATA)>
<!ELEMENT utc_d (#PCDATA)>
<!ELEMENT temp ((t_calc, t_hr, t_max, t_min))>
<!ELEMENT t_min (#PCDATA)>
<!ATTLIST t_min
	flag (3 | 0) #REQUIRED
>
<!ELEMENT t_max (#PCDATA)>
<!ATTLIST t_max
	flag (3 | 0) #REQUIRED
>
<!ELEMENT t_hr (#PCDATA)>
<!ELEMENT t_calc (#PCDATA)>
<!ELEMENT t_50 (#PCDATA)>
<!ELEMENT t_5 (#PCDATA)>
<!ELEMENT t_20 (#PCDATA)>
<!ELEMENT t_100 (#PCDATA)>
<!ELEMENT t_10 (#PCDATA)>
<!ELEMENT t (#PCDATA)>
<!ATTLIST t
	flag (3 | 0) #REQUIRED
>
<!ELEMENT sur ((t, t_max, t_min))>
<!ATTLIST sur
	type (U | R | C) #REQUIRED
>
<!ELEMENT station ((wbanno, longitude, latitude, set+))>
<!ELEMENT solar ((avg, max, min))>
<!ELEMENT soil ((moist_50, moist_100, t_5, t_10, t_20, t_50, t_100))>
<!ELEMENT set ((utc_d, utc_t, crx_vn, temp, solar, sur, rh_hr, soil))>
<!ELEMENT rh_hr (#PCDATA)>
<!ATTLIST rh_hr
	flag (3 | 0) #REQUIRED
>
<!ELEMENT moist_50 (#PCDATA)>
<!ELEMENT moist_100 (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ATTLIST min
	flag (3 | 0) #REQUIRED
>
<!ELEMENT max (#PCDATA)>
<!ATTLIST max
	flag (3 | 0) #REQUIRED
>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT crx_vn (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ATTLIST avg
	flag (3 | 0) #REQUIRED
>

=== Ancro/massive-nemesis/compressed_small.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="CRNH0203-2013-CO_Dinosaur_2_E.xsl"?><!DOCTYPE station SYSTEM "CRNH0203-2013-CO_Dinosaur_2_E.dtd"><station xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CRNH0203-2013-CO_Dinosaur_2_E.xsd"><wbanno>94082</wbanno><longitude>-108.97</longitude><latitude>40.24</latitude><set><utc_d>20130101</utc_d><utc_t>0100</utc_t><dl_vn>2.412</dl_vn><temp><avg>-11.2</avg><hr>-10.8</hr><max>-10.3</max><min>-11.2</min></temp><solar><avg flag="0">0</avg><max flag="0">0</max><min flag="0">0</min></solar><sur type="C"><avg flag="0">-15.1</avg><max flag="0">-14.5</max><min flag="0">-16.1</min></sur><rh flag="0">87</rh><soil><m_50>0.186</m_50><m_100>0.224</m_100><t_5>-1.2</t_5><t_10>-0.3</t_10><t_20>0.9</t_20><t_50>2.6</t_50><t_100>5.1</t_100></soil></set><set><utc_d>20130101</utc_d><utc_t>0200</utc_t><dl_vn>2.412</dl_vn><temp><avg>-12.7</avg><hr>-12.3</hr><max>-11.0</max><min>-13.5</min></temp><solar><avg flag="0">0</avg><max flag="0">0</max><min flag="0">0</min></solar><sur type="C"><avg flag="0">-19.4</avg><max flag="0">-16.1</max><min flag="0">-20.8</min></sur><rh flag="0">85</rh><soil><m_50>0.187</m_50><m_100>0.227</m_100><t_5>-1.1</t_5><t_10>-0.3</t_10><t_20>0.9</t_20><t_50>2.6</t_50><t_100>5.1</t_100></soil></set><set><utc_d>20130101</utc_d><utc_t>0300</utc_t><dl_vn>2.412</dl_vn><temp><avg>-12.7</avg><hr>-12.6</hr><max>-11.7</max><min>-13.6</min></temp><solar><avg flag="0">0</avg><max flag="0">0</max><min flag="0">0</min></solar><sur type="C"><avg flag="0">-20.5</avg><max flag="0">-20.0</max><min flag="0">-21.0</min></sur><rh flag="0">84</rh><soil><m_50>0.187</m_50><m_100>0.224</m_100><t_5>-1.1</t_5><t_10>-0.3</t_10><t_20>0.9</t_20><t_50>2.6</t_50><t_100>5.1</t_100></soil></set><set><utc_d>20130101</utc_d><utc_t>0400</utc_t><dl_vn>2.412</dl_vn><temp><avg>-14.7</avg><hr>-14.1</hr><max>-12.7</max><min>-15.5</min></temp><solar><avg flag="0">0</avg><max flag="0">0</max><min flag="0">0</min></solar><sur type="C"><avg flag="0">-20.7</avg><max flag="0">-20.0</max><min flag="0">-21.8</min></sur><rh flag="0">84</rh><soil><m_50>0.187</m_50><m_100>0.227</m_100><t_5>-1.1</t_5><t_10>-0.3</t_10><t_20>0.9</t_20><t_50>2.6</t_50><t_100>5.1</t_100></soil></set><set><utc_d>20130101</utc_d><utc_t>0500</utc_t><dl_vn>2.412</dl_vn><temp><avg>-13.0</avg><hr>-13.6</hr><max>-13.0</max><min>-14.7</min></temp><solar><avg flag="0">0</avg><max flag="0">0</max><min flag="0">0</min></solar><sur type="C"><avg flag="0">-20.2</avg><max flag="0">-19.2</max><min flag="0">-21.6</min></sur><rh flag="0">85</rh><soil><m_50>0.187</m_50><m_100>0.227</m_100><t_5>-1.2</t_5><t_10>-0.3</t_10><t_20>0.9</t_20><t_50>2.5</t_50><t_100>5.1</t_100></soil></set></station><!-- Total number of updates / data sets: 5 -->
